version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:latest-node-browsers
        environment:
          MIX_ENV: test
          # The following is set due to a "SHELL environment variable not set!" message appearing
          # in the logs.
          SHELL: /bin/bash

    working_directory: ~/phoenix-diff

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      # Mix dependencies
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run:
          name: Fetch and compile dependencies
          command: mix do deps.get, compile

      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"

      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run:
          name: Run tests
          command: mix test

      - store_test_results:
          path: _build/test/lib/phoenix_diff
